@startuml
actor User as U
database "Reports Database" as DB

rectangle "Capital Cities Reports" {
  usecase "Specify Criteria" as UC1
  usecase "All World Capital Cities" as UC2
  usecase "All Continent Capital Cities" as UC3
  usecase "All Region Capital Cities" as UC4
  usecase "Access Capital Cities Data" as UC5

  U --> UC1: include
  UC1 --> UC2 : include
  UC1 --> UC3 : include
  UC1 --> UC4 : include
  UC2 --> UC5 : include
  UC3 --> UC5 : include
  UC4 --> UC5 : include
}

UC5 --> DB : Query
@enduml
