@startuml
actor User as U
database "Reports Database" as DB

rectangle "Cities Reports" {
  usecase "Specify Criteria" as UC1
  usecase "Generate World Cities Report" as UC2
  usecase "Generate Continent Cities Report" as UC3
  usecase "Generate Region Cities Report" as UC4
  usecase "Generate Country Cities Report" as UC5
  usecase "Generate District Cities Report" as UC6
  usecase "Access Cities Data" as UC7

  U --> UC1 : Initiates
  UC1 --> UC2 : include
  UC1 --> UC3 : include
  UC1 --> UC4 : include
  UC1 --> UC5 : include
  UC1 --> UC6 : include
  UC2 --> UC7 : include
  UC3 --> UC7 : include
  UC4 --> UC7 : include
  UC5 --> UC7 : include
  UC6 --> UC7 : include
}

UC7 --> DB : Query
@enduml
