@startuml
actor User as U
database "Reports Database" as DB

rectangle "Population Reports" {
  usecase "Request Report" as UC1
  usecase "Continent Population" as UC2
  usecase "Region Population" as UC3
  usecase "Country Population" as UC4
  usecase "Access Population Data" as UC5

  U --> UC1    :include
  UC1 --> UC2 :include
  UC1 --> UC3 :include
  UC1 --> UC4 :include
  UC2 --> UC5 :include
  UC3 --> UC5 :include
  UC4 --> UC5 :include
}

UC5 --> DB : Query
@enduml
