version: '3'
services:
  app:
    build: .
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'world'
      MYSQL_ROOT_PASSWORD: 'example'
    ports:
      - "3306:3306"
