name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Build and run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package
      - name: Run docker compose
        run: docker-compose up --abort-on-container-exit

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run all unit tests
        run: mvn test

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: world
        ports:
          - 3306:3306 # Maps the default MySQL port to the same port on the host
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
            echo "Waiting for MySQL to be up..."
            sleep 2
          done

      - name: Integration Tests
        run: mvn verify
        env:
          # Use environment variables to configure your application's database connection
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_DB: world

